name: firebase_auth_youtube
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  cupertino_icons: ^1.0.6
  
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_iconly: ^1.0.2
  shared_preferences: ^2.3.2
  image_picker: ^0.8.5+3
  product_repository:
    path: packages/product_repository

  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/  # Add this line to include the entire assets folder
